#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#

#Theme
include kitty-theme.conf

#Font
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12

#Mouse
shell_integration no-cursor

#Cursor
cursor_blink_interval       0.5
cursor_stop_blinking_after  15

# Window Layout
remember_window_position   no
hide_window_decorations    yes
window_padding_width       7

# Close window
confirm_os_window_close    0


#Background
background_opacity         0.97
background_blur            1
dynamic_background_opacity no

#Perfomance Tuning
sync_to_monitor yes

#Keyboard action clipboard
map ctrl+shift+c   copy_to_clipboard
map ctrl+shift+v   paste_from_clipboard

#Keyboard Scroll option
map ctrl+shift+up    scroll_line_up
map ctrl+shift+down  scroll_line_down

#Keyboard Scroll page up and down option
map ctrl+shift+page_up     scroll_home
map ctrl+shift+page_down   scroll_end

#Create or delete window
map ctrl+shift+enter   new_window
map ctrl+shift+w       close_window

#Naviguate between window
map ctrl+shift+&     next_window
map ctrl+shift+é     previous_window

#Audio
enable_audio_bell    no